export const locationList = [ 
    {
    id:0, 
    title:"Malawi Adventure",
    category:"remote",
    secondcategory:"small expenditure",
    description:"Embarking on a vacation in Malawi is truly a captivating and enriching experience, enticing travelers with its  remarkable natural beauty and warm, welcoming spirit. Nestled in the southeastern region of Africa, Malawi is a hidden gem that unfolds with a tapestry of awe-inspiring landscapes and diverse ecosystem.",
    writerName:"Allison FakeName",
    writerPic:"",
    writtenOn:"May 36th, 2045",
    image:'../rename/beach4.jpeg',
    },
    
    { 
        id:1, 
        title:"Malawi Adventure",
        category:"remote",
        secondcategory:"small expenditure",
        description:"The majestic Lake Malawi, a shimmering jewel in the heart of the country, beckons adventures with its crystal-clear turquoise waters, prisitine sandy beaches, and vibrant marine life! Snorkeling, diving, or simply basking in the sun on the tranquil shores offer a sense of tranquility and rejuvenation.",
        writerName:"Roberto FakeNamo",
        writerPic:"",
        writtenOn:"May 29th, 2045",
        image:"../rename/beach5.jpeg",
    },

    {
        id:2, 
        title:"Malawi Adventure",
        category:"remote",
        secondcategory:"small expenditure",
        description: "Beyond the captivating waters, Malawis landscape unveils a stunning array of lush forests, picturesque tea platations, and dramatic mountain ranges. The iconic Mount Mulanje, stnading tall with its rugged peaks and verdant slopes, invites hikers and nature enthusiasts to explore its hidden trails, rewarding them with breathtaking vistas and a profound sense of accomplishment. Amidst this natural splendor, wildlife thrives in the country's national parks and reserves, such as Liwonde National Park and Majete Wildlife Reserve.",
        writerName:"Jersey FakeName",
        writerPic:"",
        writtenOn:"May 14th, 2045",
        image:"./rename/beach3.jpeg",
    }, 

    {
        id:3, 
        title:"The Great Greece",
        category:"remote",
        secondcategory:"small expenditure",
        description:" Greece is blessed with stunning natural beauty, from it's rugged mountains to its sparkling beaches. Whether you're looking for a relaxing beach vacation or an adventurous hiking trip - Greece truly has something to offer for visitors alike. Greek cuisine is some of the most delicious in the world and the country is home to a thriving wine industry. From fresh seafood to moussaka to baklava, there are endless culinary delights to sample in Greece.",
        writerName:"Christiano FakeNamo",
        writerPic:"",
        writtenOn:"May 19th, 2045",
        image:"./rename/beach4.jpeg",
    },

    {
        id:4, 
        title:"The Great Greece",
        category:"remote",
        secondcategory:"small expenditure",
        description: "Greeks are known for their warm hospitality, and you're sure to feel welcome in any corner of the country. Whether you're lost in a city or hiking in the mountains, you're always likel;y to be met with a smile and a helping hand. Also the capital of Greece, Athens is home to the Acropolis. the Parthenon, and other ancient ruins. It's also a great place to explore the city's vibrant nightlife and food scene.",
        writerName:"Larry FakeName",
        writerPic:"",
        writtenOn:"March 40th, 2045",
        image:"./rename/beach5.jpeg",
    },

    {
        id:5, 
        title:"The Great Greece",
        category:"remote",
        secondcategory:"small expenditure",
        description: "Santorini is a top tourist destination in Greece. The volcanic island is known for its whitewashed villages, stunning caldera views, and blacksand beaches. Mykonos is another popular island destination, its known for its party atmosphere, beautiful beaches and trendy bars and amazing nightlife. ",
        writerName:"Tanto FakeNamo",
        writerPic:"",
        writtenOn:"March 10th, 2045",
        image:"./rename/beach6.jpeg",
    },


    {
        id:6, 
        title:"A Haunted Maine land",
        category:"remote",
        secondcategory:"small expenditure",
        description: "Maine is home to some of the most beautiful scenery in the United States, from it's rugged coastline to its lush forests to its craggy mountains. I love it here because it is a great place to escape the hustle and bustly of city life and connect with nature. There are countless opportunities for hiking, camping, fishing and a plethora of other outdoor activities. ",
        writerName:"Woody FakeName",
        writerPic:"",
        writtenOn:"March 09th, 2045",
        image:"./rename/beach7.jpeg",
    },

    {
        id:7, 
        title:"A Haunted Maine land",
        category:"remote",
        secondcategory:"small expenditure",
        description: "As a self proclaimed foodie, the fresh seafood in Main from their famoous lobsters to clams to scallops are greatly enjoyable. There are countless restaurants and markets where you can enjoy these delicious delicacies. Main is home to many charming towns and villages, each with it's own unique history and beautiful character. Wandering through centuries-old streets, you'll think you wandered into the great mystery novel created.",
        writerName:"Nemo FakeNamo",
        writerPic:"",
        writtenOn:"June 29th, 2045",
        image:"./rename/beach8.jpeg",
    },

    {
        id:8, 
        title:"Norwegian Escape",
        category:"remote",
        secondcategory:"small expenditure",
        description: "Vacationing in Norway promises an unforgettable and exhilarating experience, where breathtaking natural wonders, captivating cultural heritage, and thrilling outdoor adventures converge. This Nordic gem, with its rugged fjords, towering mountains, and awe-inspiring landscapes, offers a playground for nature enthusiasts and adventure seekers alike. The iconic fjords, such as the majestic Geirangerfjord and the serene Sognefjord, showcase nature's grandeur, inviting visitors to embark on the scenic cruises, kayak expeditions, or hike along picturesque trails that lead to panoramic viewpoints.",
        writerName:"Dory FakeNamy",
        writerPic:"",
        writtenOn:"June 5th, 2045",
        image:"./rename/beach9.jpeg",
    },

    {
        id:9, 
        title:"Norwegian Escape",
        category:"remote",
        secondcategory:"small expenditure",
        description: "Norway's prisitine wilderness extends beyond the fjords, encompassing vast national parks like Jotunheimen and Hardangervidda, where visitors can engage in activities like hikinh, skiing, or even witnessing the mesmerizing Northern Lights in winter. ",
        writerName:"Todd FakeName",
        writerPic:"",
        writtenOn:"August 19th, 2045",
        image:"./rename/beach10.jpeg",
    },

    {
        id:10, 
        title:"Norwegian Escape",
        category:"remote",
        secondcategory:"small expenditure",
        description:" The country's rich cultural heritage is equally captivating, with charming towns like Bergen and Trondheim offering a glimpse into Norway's history and traditions. Delving into the Viking heritage at historial sites such as the Viking Ship Museum in Osloadds an intriguing dimension to the journey. Moreever, the warmth and the friendliness of the Norwegian people, combined with their emphasis on a sustainable tourism, enhance the overall experience, making a vacation in Norway truly fun and rewarding.",
        writerName:"Wednesday FakeNamy",
        writerPic:"",
        writtenOn:"November 7th, 2045",
        image:"./rename/beach11.jpeg",
    },

    {
        id:11, 
        title:"Thailand Wonder",
        category:"remote",
        secondcategory:"small expenditure",
        description:" Vacationing in Thailand is an extraordinary adventure as well as priviledge - it's regarded as one of the top travel destinations in the world. The Land of Smiles seamlessly blends ancient traditions with modern marvels, immersing visitors in a kaleidoscope of experiences. Thailand's pristine tropical beaches, like those found in Phuket, Krabi or Koh Samui, allure sunseekers with their powdery sands, azure waters, and idyllic palm-fringed shorelines. ",
        writerName:"Forrest FakeName",
        writerPic:"",
        writtenOn:"Novemnber 4th, 2045",
        image:"./rename/beach12.jpeg",
    },

    {
        id:12, 
        title:"Thailand Wonder",
        category:"remote",
        secondcategory:"small expenditure",
        description: "Whether it's swimming, snorkeling, or simply indulging in a relaxing beachside massage, the coastal paradise of Thailand offers unparalleled relaxation and rejuvenation. Beyond the coastline, Thailand's rich cultural heritage awaits exploration. From dazzling Buddhist temples, like that of Wat Arun and Wat Phra Kaew in Bangkik, to the enchanting anciet city of Ayuthaya, the country boasts a treasure trove of architectural wonders and historial landmarks. ",
        writerName:"Toto FakeNamo",
        writerPic:"",
        writtenOn:"December 7th, 2045",
        image:"./rename/beach13.jpeg",
    },

    {
        id:13, 
        title:"Thailand Wonder",
        category:"remote",
        secondcategory:"small expenditure",
        description: "The bustiling markets and vibrant street food scene offer a tantalizing gastronomic experience, where flavorsome dishes like pad Thai, green curym and mango sticky rice tantalize the taste buds. For adventure seekers, Thailand's lush jungles and national parks, like Khao Yai and Doi Inthanon, present opportunities for exhilarating trekking, wildlife spotting and breathtaking encounters with nature. The warmth and friendliness of the Thai people, known for their genuine hospitality, further enhance the overall appeal of this captivating country, leaving visitors with cherised memroies that linger long after their departure.",
        writerName:"Great FakeName",
        writerPic:"",
        writtenOn:"December 20th, 2045",
        image:"./rename/beach14.jpeg",
    }

]