export const locationList = [ 
    {
    id:0, 
    title:"Malawi Adventure",
    category:"remote",
    secondcategory:"small expenditure",
    description: "",
    writerName:"",
    writerPic:"",
    writtenOn:"May 36th, 2045",
    image:'./rename/beach1.jpeg',
    },
    
    { 
        id:1, 
        title:"Malawi Adventure",
        category:"remote",
        secondcategory:"small expenditure",
        description: "",
        writerName:"",
        writerPic:"",
        writtenOn:"May 29th, 2045",
        image:"./rename/beach2.jpeg",
    },

    {
        id:2, 
        title:"Malawi Adventure",
        category:"remote",
        secondcategory:"small expenditure",
        description: "",
        writerName:"",
        writerPic:"",
        writtenOn:"May 14th, 2045",
        image:"./rename/beach3.jpeg",
    }, 

    {
        id:3, 
        title:"Malawi Adventure",
        category:"remote",
        secondcategory:"small expenditure",
        description: "",
        writerName:"",
        writerPic:"",
        writtenOn:"May 19th, 2045",
        image:"./rename/beach4.jpeg",
    },

    {
        id:4, 
        title:"Malawi Adventure",
        category:"remote",
        secondcategory:"small expenditure",
        description: "",
        writerName:"",
        writerPic:"",
        writtenOn:"March 40th, 2045",
        image:"./rename/beach5.jpeg",
    },

    {
        id:5, 
        title:"A Haunted Maine Land",
        category:"remote",
        secondcategory:"small expenditure",
        description: "",
        writerName:"",
        writerPic:"",
        writtenOn:"March 10th, 2045",
        image:"./rename/beach6.jpeg",
    },


    {
        id:6, 
        title:"A Haunted Maine land",
        category:"remote",
        secondcategory:"small expenditure",
        description: "",
        writerName:"",
        writerPic:"",
        writtenOn:"March 09th, 2045",
        image:"./rename/beach7.jpeg",
    },

    {
        id:7, 
        title:"A Haunted Maine land",
        category:"remote",
        secondcategory:"small expenditure",
        description: "",
        writerName:"",
        writerPic:"",
        writtenOn:"June 29th, 2045",
        image:"./rename/beach8.jpeg",
    },

    {
        id:8, 
        title:"Malawi Adventure",
        category:"remote",
        secondcategory:"small expenditure",
        description: "",
        writerName:"",
        writerPic:"",
        writtenOn:"June 5th, 2045",
        image:"./rename/beach9.jpeg",
    },

    {
        id:9, 
        title:"Norwegian Escape",
        category:"remote",
        secondcategory:"small expenditure",
        description: "",
        writerName:"",
        writerPic:"",
        writtenOn:"August 19th, 2045",
        image:"./rename/beach10.jpeg",
    },

    {
        id:10, 
        title:"Norwegian Escape",
        category:"remote",
        secondcategory:"small expenditure",
        description: "",
        writerName:"",
        writerPic:"",
        writtenOn:"November 7th, 2045",
        image:"./rename/beach11.jpeg",
    },

    {
        id:11, 
        title:"Norwegian Escape",
        category:"remote",
        secondcategory:"small expenditure",
        description: "",
        writerName:"",
        writerPic:"",
        writtenOn:"Novemnber 4th, 2045",
        image:"./rename/beach12.jpeg",
    },

    {
        id:12, 
        title:"Thailand Wonder",
        category:"remote",
        secondcategory:"small expenditure",
        description: "",
        writerName:"",
        writerPic:"",
        writtenOn:"December 7th, 2045",
        image:"./rename/beach13.jpeg",
    },

    {
        id:13, 
        title:"Thailand Wonder",
        category:"remote",
        secondcategory:"small expenditure",
        description: "",
        writerName:"",
        writerPic:"",
        writtenOn:"December 20th, 2045",
        image:"./rename/beach14.jpeg",
    }

]